name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ USERNAME }}
          password: ${{ PAT }}
      - name: Build the rabbit Docker image
        run: |
              docker build -t ghcr.io/benhassan98/rabbit:latest .
              docker push ghcr.io/benhassan98/rabbit:latest
     
