name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ benHassan98 }}
          password: ${{ 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 }}
      - name: Build the rabbit Docker image
        run: |
              docker build -t ghcr.io/benhassan98/rabbit:latest .
              docker push ghcr.io/benhassan98/rabbit:latest
     
